Quick port forwarding - check for iptables rules

diff --git a/in b/in
--- a/in
+++ b/in
@@ -1,56 +1,135 @@
 #!/bin/bash
-# Check inputs
+
+# Check input port
 check_port(){
-if ! [ "$1" -eq "$1" >& /dev/null ];then
-  return 1
+if ! [ "$2" -eq "$2" >& /dev/null ];then
+  status=1
 else
-	if [ $1 -lt 65536 ]; then
-		return 0
+	if [ $2 -lt 65536 ]; then
+		status=0
+		portnum=$2
 	else
-		return 1
+		status=1
 	fi
 fi
+if [ $status -ne 0 ]; then
+  if !  grep -q -w ^$2\  /etc/services  ; then
+    echo "Specify usable port number"
+    exit
+  else
+    portnum=$( getent services $2 |awk '{split($2,a,"/");print a[1]}')
+    if [ $? -ne 0 ]; then
+      echo "Specify usable port number"
+      exit
+		fi
+	fi
+fi
+echo $portnum
 }
+
+
+get_help(){
+cat <<HERE
+Allow remote access to a named qube.
+
+Specify target qube, action, tcp or udp, and target port, separated by spaces.
+The target port can be given by port number or by name (e.g ssh).
+The action should be "add" or "delete".
+For example:
+	in target_qube add tcp 80 
+	in target_qube add tcp ssh 
+	in target_qube delete tcp https 
+
+DO NOT use this script for qubes behind a Tor or VPN proxy.
+At a minimum you risk breaking the security of those proxies.
+
+By default, the script will open a port on the final netvm which is the same as the target port.
+
+HERE
+exit
+}
+
 
 get_handle(){
 local my_handle=$( qvm-run -q -u root -p $1 " nft -a list table $2|awk 'BEGIN{c=0} /$3/{c++; if (c==$4) print \$NF}' " )
 echo $my_handle
 }
 
+
+#Tunnel through netvms
 tunnel(){
 declare -a my_netvms=("${!1}")
 declare -a my_ips=("${!2}")
 declare -i numhops
 numhops=${#my_ips[@]}
+lasthop=$((numhops-1))
 local i=1
 iface="eth0"
-numhops=$((numhops-1))
-while [ $i -ne $numhops ]
-do
-	qvm-run -q -u root ${my_netvms[$i]} " nft list table nat|grep ' $proto dport $portnum dnat to ${my_ips[$i-1]}'"
-	if [ $? -eq 0 ]; then
-		echo "Are rules already set?"
-		exit
-	else
-		qvm-run -q -u root ${my_netvms[$i]} -- nft insert rule nat PR-QBS meta iifname $iface $proto dport $portnum dnat to ${my_ips[$i-1]}
-		local handle=$( get_handle ${my_netvms[$i]} filter related,established 2 )
-		qvm-run -q -u root ${my_netvms[$i]} -- nft add rule filter FORWARD position $handle meta iifname $iface ip daddr ${my_ips[$i-1]} $proto dport $portnum ct state new accept
-	fi
-	((i++))
-done
-qvm-run -q -u root ${my_netvms[$i]} " nft list table nat|grep ' $proto dport $portnum dnat to ${my_ips[$i-1]}'"
+qvm-run -q -u root ${my_netvms[$lasthop]} " nft list table nat|grep ' $proto dport $portnum dnat to ${my_ips[$numhops-1]}'"
 if [ $? -eq 0 ]; then
 	echo "Are rules already set?"
 	exit
-else
-	qvm-run -q -u root ${my_netvms[$i]} -- nft insert rule nat PR-QBS meta iifname $external_iface $proto dport $portnum dnat to ${my_ips[$i-1]}
-	qvm-run -q -u root ${my_netvms[$i]} -- nft insert rule filter FORWARD meta iifname $external_iface ip daddr ${my_ips[$i-1]} $proto dport $portnum ct state new accept
 fi
+while [ $i -ne $numhops ]
+do
+	echo  ${my_netvms[$i]}
+	if [ $i -eq $lasthop ]; then
+		iface=$external_iface
+	fi
+	# Is it nft or iptables?
+	local found=$( qvm-run -p -q -u root ${my_netvms[$i]} -- nft list table nat 2>/dev/null )
+	if [[ x$found == 'x' ]]; then
+		qvm-run -q -u root ${my_netvms[$i]} -- iptables -I QBS-FORWARD -i $iface -p $proto --dport $portnum -d ${my_ips[$i-1]} -j ACCEPT
+		qvm-run -q -u root ${my_netvms[$i]} -- iptables -t nat -I PR-QBS-SERVICES -i $iface -p $proto --dport $portnum -j DNAT --to-destination ${my_ips[$i-1]}
+	else
+		qvm-run -q -u root ${my_netvms[$i]} -- nft insert rule nat PR-QBS-SERVICES meta iifname $iface $proto dport $portnum dnat to ${my_ips[$i-1]}
+		qvm-run -q -u root ${my_netvms[$i]} -- nft insert rule filter QBS-FORWARD meta iifname $iface ip daddr ${my_ips[$i-1]} $proto dport $portnum ct state new accept
+	fi
+	((i++))
+done
 }
 
-if [ $# -ne 3 ]; then
-  echo "Please specify target qube, tcp or udp, and target port"
-  exit
+
+#Teardown - from top netvm down
+teardown(){
+declare -a my_netvms=("${!1}")
+declare -a my_ips=("${!2}")
+declare -i numhops
+numhops=${#my_ips[@]}
+numhops=$((numhops-1))
+local i=$numhops
+iface="eth0"
+echo "Removing all firewall rules"
+while [ $i -gt 0 ]
+do
+	# Is it nft or iptables?
+	echo "${my_netvms[$i]}"
+	local found=$( qvm-run -p -q -u root ${my_netvms[$i]} -- nft list table nat 2>/dev/null )
+ 	if [[ x$found == 'x' ]]; then
+		qvm-run -q -u root ${my_netvms[$i]} -- iptables -D QBS-FORWARD -i $iface -p $proto --dport $portnum -d ${my_ips[$i-1]} -j ACCEPT
+		qvm-run -q -u root ${my_netvms[$i]} -- iptables -t nat -D PR-QBS-SERVICES -i $iface -p $proto --dport $portnum -j DNAT --to-destination ${my_ips[$i-1]}
+	else
+		local handle=$( get_handle ${my_netvms[$i]} nat "dport $portnum" 1 )
+		qvm-run -q  -u root ${my_netvms[$i]} -- nft delete rule nat PR-QBS-SERVICES handle $handle
+		local handle=$( get_handle ${my_netvms[$i]} filter "dport $portnum" 1 )
+		qvm-run -q -u root ${my_netvms[$i]} -- nft delete rule filter QBS-FORWARD handle $handle
+	fi
+	((i--))
+done
+local found=$( qvm-run -p -q -u root ${my_netvms[$i]} -- nft list table nat 2>/dev/null )
+if [[ x$found == 'x' ]]; then
+	qvm-run -q -u root ${my_netvms[$i]} " iptables -D INPUT -p $proto --dport $portnum -j ACCEPT"
+else
+	handle=$( get_handle ${my_netvms[$i]} filter "dport $portnum" 1 )
+	qvm-run -q -u root ${my_netvms[$i]} -- nft delete rule filter INPUT handle $handle
+fi
+exit
+}
+
+
+## Check inputs
+if [ $# -lt 4 ]; then
+	get_help
 fi
 qvm-check -q $1 2>/dev/null
 if [ "$?" -ne 0 ];then
@@ -59,28 +138,13 @@ if [ "$?" -ne 0 ];then
 else
 	qube_name=$1
 fi
-if [ "$2" != "tcp" -a "$2" != "udp" ]; then
+if [ "$3" != "tcp" -a "$3" != "udp" ]; then
   echo "Specify tcp or udp"
   exit
 else
-	proto=$2
+	proto=$3
 fi
-check_port $3
-if [ $? -ne 0 ]; then
-  if !  grep -q -w ^$3\  /etc/services  ; then
-    echo "Specify usable port number"
-    exit
-  else
-    portnum=$( getent services $3 |awk '{split($2,a,"/");print a[1]}')
-    check_port $portnum
-    if [ $? -ne 0 ]; then
-      echo "Specify usable port number"
-      exit
-    fi
-  fi
-else
-	portnum=$3
-fi
+portnum=$(check_port $3 $4)
 
 # Get all netvms
 declare -a netvms
@@ -94,53 +158,71 @@ do
   ((hop++))
   IFS='|' read -r netvms[$hop+1] ips[$hop] <<< $(qvm-ls ${netvms[$hop]} --raw-data -O netvm,IP)
 done
-if [ $hop -eq 0 ]; then
-	echo "$qube_name is not network connected"
-  echo "Cannot set up a tunnel"
-	exit
-fi
+if [ $2 == "delete" ]; then
+	teardown netvms[@] ips[@]
+elif [ $2 == "add" ]; then
+	if [ $hop -eq 0 ]; then
+		echo "$qube_name is not network connected"
+		echo "Cannot set up a tunnel"
+		exit
+	fi
 
-# Check last hop has external IP address 
-readarray -t external_ips < <( qvm-run -p ${netvms[$hop]} "ip -4 -o a|grep -wv 'lo\|vif[0-9]*.*'"|awk '{print $2,$4}')
-#readarray -t external_ips < <( qvm-run -p ${netvms[$hop]} "ip -4 -o a|grep -wv 'vif[0-9]'"|awk '{print $2,$4}')
-num_ifs=${#external_ips[@]}
-if [ $num_ifs -eq 1 ]; then
-  interface=0
-elif [ $num_ifs -gt 1 ]; then
-  echo "${netvms[$hop-1]} has more than 1 external interface"
-  echo "Which one do you want to use?"
-  for i in $(seq $num_ifs)
-  do
-    echo "$i. ${external_ips[$i-1]}"
-  done
-  read interface
-  if ! [ "$interface" -eq "$interface" ] 2> /dev/null; then
-    echo "No such interface"
-    exit
-  elif [ $interface -gt $num_ifs ] || [ $interface -lt 1 ]; then
-    echo "No such interface"
-    exit
-  fi
-  ((interface--))
-else
-  echo "${netvms[$hop]} does not have an external interface"
+	# Check last hop has external IP address 
+	readarray -t external_ips < <( qvm-run -p ${netvms[$hop]} "ip -4 -o a|grep -wv 'lo\|vif[0-9]*.*'"|awk '{print $2,$4}')
+	#readarray -t external_ips < <( qvm-run -p ${netvms[$hop]} "ip -4 -o a|grep -wv 'vif[0-9]'"|awk '{print $2,$4}')
+	num_ifs=${#external_ips[@]}
+	if [ $num_ifs -eq 1 ]; then
+		interface=0
+	elif [ $num_ifs -gt 1 ]; then
+		echo "${netvms[$hop]} has more than 1 external interface"
+		echo "Which one do you want to use?"
+		for i in $(seq $num_ifs)
+		do
+			echo "$i. ${external_ips[$i-1]}"
+		done
+		read interface
+		if ! [ "$interface" -eq "$interface" ] 2> /dev/null; then
+			echo "No such interface"
+			exit
+		elif [ $interface -gt $num_ifs ] || [ $interface -lt 1 ]; then
+			echo "No such interface"
+			exit
+		fi
+		((interface--))
+	else
+		echo "${netvms[$hop]} does not have an external interface"
   echo "Cannot set up a tunnel"
   exit
-fi
-external_ip=${external_ips[$interface]}
-external_iface="${external_ip%[[:space:]]*}"
-ip="${external_ip#*[0-9]}"
-ip="${ip%%/*}"
-ips[$hop]=$ip
+	fi
+	external_ip=${external_ips[$interface]}
+	external_iface="${external_ip%[[:space:]]*}"
+	ip="${external_ip#*[0-9]}"
+	ip="${ip%%/*}"
+	ips[$hop]=$ip
 
-# Create tunnel
-qvm-run -q -u root $qube_name  "nft list table filter|grep '$proto dport $portnum accept' "
-if [ $? -eq 0 ]; then
-	echo "Input rule in $qube_name already exists"
-	echo "Please check configuration - exiting now."
-	exit
-else
-	handle=$( get_handle $qube_name filter related,established 1)
-	qvm-run -q -u root $qube_name -- nft add rule filter INPUT position $handle iifname eth0 $proto dport $portnum accept
+	# Create tunnel
+	found=$( qvm-run -p -q -u root $qubes_name -- nft list table nat 2>/dev/null )
+ 	if [[ x$found == 'x' ]]; then
+		found=$(qvm-run -p -u root $qube_name "iptables -L -nv |grep -c '.*ACCEPT.*$proto dpt:$portnum' ")
+		if [ "$found" -gt 0 ]; then
+			echo "Input rule in $qube_name already exists"
+			echo "Please check configuration - exiting now."
+			exit
+		else
+			qvm-run -q -u root $qube_name  "iptables -I INPUT -p $proto --dport $portnum -j ACCEPT "
+		fi
+	else
+		qvm-run -q -u root $qube_name  "nft list table filter|grep '$proto dport $portnum accept' "
+		if [ $? -eq 0 ]; then
+			echo "Input rule in $qube_name already exists"
+			echo "Please check configuration - exiting now."
+			exit
+		else
+			handle=$( get_handle $qube_name filter related,established 1)
+			qvm-run -q -u root $qube_name -- nft add rule filter INPUT position $handle iifname eth0 $proto dport $portnum accept
+		fi
+	fi
 	tunnel netvms[@] ips[@]
+else
+	get_help
 fi
